{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-multica
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/multiCA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/multiCA/multiCA_{{ version }}.tar.gz
  sha256: dc49783ea79129114b0cf48a81d1a5d2716c21bfb42eaed3f7c0b3a9cb9b056f

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bitops
    - r-multcomp
  run:
    - r-base
    - r-bitops
    - r-multcomp

test:
  commands:
    - $R -e "library('multiCA')"           # [not win]
    - "\"%R%\" -e \"library('multiCA')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=multiCA
  license: GPL-2.0-or-later
  summary: Implements a generalization of the Cochran-Armitage trend test to multinomial data. In addition to an overall test, multiple testing adjusted p-values for trend in individual outcomes and power calculation is available.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
